version: "3"
services:
  postgres:
    image: "postgres:9.6"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "3052:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./api/data:/data_import 

  webserver:
    build: .
    container_name: "modeltrainer"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./airflow_files/dags:/usr/local/airflow/dags
      - ./airflow_files/logs:/usr/local/airflow/logs
      - ./airflow_files/packages:/usr/local/airflow/packages
      - ./airflow_files/plugins:/usr/local/airflow/plugins
    ports:
      - "3053:8080"
      - "3054:5555"
      - "3055:8793"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid]"]
      interval: 30s
      timeout: 30s
      retries: 3
    
  geotrainer:
    container_name: 'geotrainer'
    build: ./api
    ports:
      - "3056:6767"
    command: develop
    volumes:
      - ./api/GeoTrainer:/api/GeoTrainer
    depends_on:
    - postgres

    restart: always
    env_file:
      - .env
    environment:
      PORT: 6767
      HOST: "0.0.0.0"
      database: test
      CT_REGISTER_MODE: auto
      ENVIRONMENT: dev
      DEBUG: "True"
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
      API_VERION: v1
      user: postgres
      password: postgres
      psqlPort: 5432
