apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: mt-webserver
  name: mt-webserver
spec:
  ports:
    - port: 8080
      name: airflow
  selector:
    name: mt-webserver
