apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: mt-webserver
  name: mt-webserver
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    name: mt-webserver